/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvyWatermark {
        "content": string;
        "fontColor": string;
        "fontFamily": string;
        "fontSize": string;
        "fontStyle": string;
        "fontWeight": string;
        "gapX": string;
        "gapY": string;
        "height": string;
        "offsetX": string;
        "offsetY": string;
        "rotate": string;
        "width": string;
        "zIndex": string;
    }
}
declare global {
    interface HTMLIvyWatermarkElement extends Components.IvyWatermark, HTMLStencilElement {
    }
    var HTMLIvyWatermarkElement: {
        prototype: HTMLIvyWatermarkElement;
        new (): HTMLIvyWatermarkElement;
    };
    interface HTMLElementTagNameMap {
        "ivy-watermark": HTMLIvyWatermarkElement;
    }
}
declare namespace LocalJSX {
    interface IvyWatermark {
        "content"?: string;
        "fontColor"?: string;
        "fontFamily"?: string;
        "fontSize"?: string;
        "fontStyle"?: string;
        "fontWeight"?: string;
        "gapX"?: string;
        "gapY"?: string;
        "height"?: string;
        "offsetX"?: string;
        "offsetY"?: string;
        "rotate"?: string;
        "width"?: string;
        "zIndex"?: string;
    }
    interface IntrinsicElements {
        "ivy-watermark": IvyWatermark;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ivy-watermark": LocalJSX.IvyWatermark & JSXBase.HTMLAttributes<HTMLIvyWatermarkElement>;
        }
    }
}
