/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvyWatermark {
        "zIndex": string;
    }
    interface UniWatermark {
    }
}
declare global {
    interface HTMLIvyWatermarkElement extends Components.IvyWatermark, HTMLStencilElement {
    }
    var HTMLIvyWatermarkElement: {
        prototype: HTMLIvyWatermarkElement;
        new (): HTMLIvyWatermarkElement;
    };
    interface HTMLUniWatermarkElement extends Components.UniWatermark, HTMLStencilElement {
    }
    var HTMLUniWatermarkElement: {
        prototype: HTMLUniWatermarkElement;
        new (): HTMLUniWatermarkElement;
    };
    interface HTMLElementTagNameMap {
        "ivy-watermark": HTMLIvyWatermarkElement;
        "uni-watermark": HTMLUniWatermarkElement;
    }
}
declare namespace LocalJSX {
    interface IvyWatermark {
        "zIndex"?: string;
    }
    interface UniWatermark {
    }
    interface IntrinsicElements {
        "ivy-watermark": IvyWatermark;
        "uni-watermark": UniWatermark;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ivy-watermark": LocalJSX.IvyWatermark & JSXBase.HTMLAttributes<HTMLIvyWatermarkElement>;
            "uni-watermark": LocalJSX.UniWatermark & JSXBase.HTMLAttributes<HTMLUniWatermarkElement>;
        }
    }
}
